echo "Complex concatenation: $USER-$HOME-$PWD"
echo "With numbers: file_$USER_123.txt"  
echo "Mixed quotes: $USER's home is $HOME"
echo "Escape patterns: \$USER and $USER"
echo "Multiple dollars: $$USER and $USER$$"
echo "Invalid vars: $NONEXISTENT_VAR_123"
echo "Special chars: $USER@domain.com"
echo "Path building: $HOME/.config/$USER/settings"
echo "Command-like: git clone $USER@github.com:$USER/repo.git"
echo "Complex nesting: ${USER}_backup_$(date)"
